#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later

# Shared helpers for the Ahwa YunoHost package. Sourced by every
# install/remove/upgrade/backup/restore script.

# Read the pinned Bun version from the repo's canonical .bun-version
# file (also consumed by the Dockerfile build-arg). Single source of
# truth so YNH installs and Docker builds stay in lockstep — bumping
# the file in one PR updates every deployment path.
read_bun_version() {
    local install_dir="$1"
    local f="$install_dir/src/.bun-version"
    if [ ! -f "$f" ]; then
        ynh_die --message="missing $f — repo is out of sync with this packaging"
    fi
    tr -d '[:space:]' < "$f"
}

# Install Bun into the per-app install_dir. Vendoring Bun per-app keeps
# YNH backup/restore self-contained and avoids depending on a system
# Bun that an admin might upgrade or remove behind our back.
install_bun() {
    local install_dir="$1"
    local version
    version="$(read_bun_version "$install_dir")"
    export BUN_INSTALL="$install_dir/.bun"
    # The Bun installer reads $HOME to update shell rc files. YNH scripts
    # run with `set -u`, and HOME isn't set in the install context, so the
    # installer trips on "HOME: unbound variable". Pin HOME to the install
    # dir — Bun's rc-file edits land in $install_dir/.bashrc which we don't
    # care about anyway.
    export HOME="$install_dir"
    mkdir -p "$BUN_INSTALL"
    curl -fsSL "https://bun.sh/install" | bash -s "bun-v${version}"
}

# Path to the bun binary inside an install_dir.
bun_bin() {
    local install_dir="$1"
    echo "$install_dir/.bun/bin/bun"
}

# Render $install_dir/.env from the install/config-panel settings:
#   $llm_provider  one of openrouter|anthropic|openai|ollama
#   $llm_api_key   key (ignored for ollama)
#   $ollama_url    base URL (ignored unless provider=ollama)
#   $share_secret  hex secret for share-link signing
#
# The systemd unit loads this via EnvironmentFile=-$install_dir/.env, so
# the variables become process env without ever appearing in `ps` or in
# /etc/systemd/system/ahwa.service. Mode 600 + chown to the app user.
render_env_file() {
    local install_dir="$1"
    local provider="$2"
    local api_key="$3"
    local ollama_url="$4"
    local share_secret="$5"

    local env_file="$install_dir/.env"
    {
        echo "# Generated by ahwa_ynh — edit via 'yunohost app config set ahwa'."
        echo "AHWA_SHARE_SECRET=$share_secret"
        case "$provider" in
            anthropic)  echo "ANTHROPIC_API_KEY=$api_key" ;;
            openai)     echo "OPENAI_API_KEY=$api_key" ;;
            openrouter) echo "OPENROUTER_API_KEY=$api_key" ;;
            ollama)     echo "OLLAMA_BASE_URL=$ollama_url" ;;
            *)          ynh_die --message="unknown llm_provider: $provider" ;;
        esac
    } > "$env_file"
    chown "$app:$app" "$env_file"
    chmod 600 "$env_file"
}

# Run the vendored bun as the app user, with cwd at $install_dir/src.
# Replaces three-line pushd/run/popd dances at every call site:
#
#     bun_app "install --frozen-lockfile"
#     bun_app "run build"
#
# The first arg is the install_dir; remaining args are passed through
# to bun verbatim. ynh_exec_as_app drops privileges to the system user
# YNH provisioned via [resources.system_user] in the manifest.
bun_app() {
    local install_dir="$1"
    shift
    pushd "$install_dir/src" >/dev/null || ynh_die --message="cannot enter $install_dir/src"
    ynh_exec_as_app "$install_dir/.bun/bin/bun" "$@"
    popd >/dev/null || true
}
